services:
  - type: web
    name: starbit-backend
    env: python
    region: oregon
    plan: free
    buildCommand: |
     pip install -r requirements.txt
    startCommand: |
      gunicorn logistic_project.wsgi
      python manage.py makemigrations
      python manage.py migrate
      gunicorn logistic_projec.wsgi:application
    runtime: python
    branch: main
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: starbit-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"

databases:
  - name: starbit-db
    region: oregon
    plan: free
