services:
  - type: web
    name: starbit.onrender.com
    env: python
    buildCommand: |
      pip install -r requirements.txt
    startCommand: |
  
      python manage.py makemigrations
      python manage.py migrate
      gunicorn logistic_project.wsgi:application
      