services:
  - type: web
    name: starbit.onrender.com
    env: python
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    
    startCommand: python -m gunicorn logistic_project.wsgi:application --bind 0.0.0.0:$PORT

